fixtures:
  repositories:
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
  symlinks:
    {{cookiecutter.project_name}}: "#{source_dir}"
